#load packages
library(lubridate)
library(dplyr)
library(segmented)
library(bbmle)
library(ggplot2)
library(akima)
library(mleTools)
library(reshape2)
library(mgcv)
library(tidyr)
library(tidyverse)
library(gridExtra)
library(gtable)
library(grid)
library(ggpubr)
library(ggrepel)

#Growth data generated by the growthTools package, DOI:10.5281/zenodo.3634918
library(growthTools)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#### Generating TPCs ####

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

#load data
gdat2<-read.csv("~/Data/Cyano_growth_data.csv")
  
# ids for figures
gdat2$id2<-paste(gdat2$Species, gdat2$Medium)
gdat2$id2<-as.factor(gdat2$id2)

head(gdat2)

# acclimated curves

dat.acc<-gdat2[gdat2$Acute.temp==gdat2$Acclim.temp,]
dat.acc$Temp.tx <- "D Fully acclimated"

g1<-ggplot(data.frame(dat.acc),aes(x=Acclim.temp,y=mu, linetype=Medium))+
  stat_smooth(data=dat.acc,method='gam',formula=y~s(x,k=3),colour="black")+
  geom_hline(yintercept=0)+
  scale_linetype_manual(values=c("solid", "dashed"))+
  geom_point(aes(shape=Medium), alpha=0.5,colour="black")+
  scale_shape_manual(values=c(16,1))+
  theme_bw()+
  theme(legend.position = "bottom")+
  scale_x_continuous('Temperature (°C)')+
  scale_y_continuous('Growth rate (1/day)')+
  facet_wrap(~Species)
g1

# acute nutrient curves against acclimated curve

dat.acute <- subset(gdat2,Temp.tx=="Cold" | Temp.tx=="Hot")
dat.full <- rbind(dat.acute, dat.acc)

g2<-ggplot(data.frame(dat.full),aes(x=Acute.temp,y=mu,colour=as.factor(Temp.tx),linetype=Medium))+
  stat_smooth(data=dat.full,method='gam',formula=y~s(x,k=3),aes(fill=as.factor(Temp.tx),color=as.factor(Temp.tx)))+
  scale_linetype_manual(values=c("solid","dashed"))+
  scale_color_manual(values=c("#3399FF","gray60","#FF6666"),labels=c("Cold","Fully-acclimated","Hot"))+ 
  scale_fill_manual(values=c("#3399FF","gray60","#FF6666"),labels=c("Cold","Fully-acclimated","Hot"))+
  geom_hline(yintercept=0,linetype="solid")+
  geom_point(data=dat.full,aes(shape=Medium))+
  scale_shape_manual(values=c(16,1), guide='none')+
  theme_bw()+
  guides(shape=FALSE, linetype=FALSE)+
  labs(colour = "Acclimation temperature", fill = "Acclimation temperature")+
  scale_x_continuous('Temperature (°C)')+
  scale_y_continuous('Growth rate (1/day)')
g2

Medium.labs<-c("High nutrients","Low nutrients")
names(Medium.labs)<-c("A Replete","B Limited")
g2b <- g2 + facet_grid(Species~Medium,labeller=labeller(Medium=Medium.labs),scale="free_y") + theme(legend.position = "bottom")
g2b

# figure 1 output
ggsave(filename = '~/Output/Cyano_TPCs.png',g2b,width = 7.5, height = 10, units = "in")


